// Run with NODE_PATH pointing at an installation of playwright.
// Usage: NODE_PATH=/tmp/prospector-browser/node_modules node tools/browser-check.cjs URL
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({headless: true, args: ['--no-sandbox', '--enable-webgl', '--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader']});
  const errors = [];
  const page = await browser.newPage({viewport: {width: 960, height: 640}});
  page.on('pageerror', e => errors.push(String(e)));
  page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
  page.on('response', r => { if(r.status() >= 400) errors.push(`${r.status()} ${r.url()}`); });
  const url = process.argv[2] || 'http://127.0.0.1:8000/build/web/';
  await page.goto(url);
  await page.waitForTimeout(8000);
  await page.screenshot({path: '/tmp/prospector-web-title.png'});
  await page.mouse.click(480, 335);
  await page.waitForTimeout(400);
  await page.screenshot({path: '/tmp/prospector-web-choice.png'});
  await page.mouse.click(480, 315);
  await page.waitForTimeout(500);
  await page.keyboard.down('Space');
  await page.keyboard.down('ArrowRight');
  await page.waitForTimeout(1350);
  await page.keyboard.up('Space');
  await page.keyboard.up('ArrowRight');
  await page.waitForTimeout(1700);
  await page.screenshot({path: '/tmp/prospector-web-play.png'});
  await page.keyboard.press('b');
  await page.waitForTimeout(250);
  await page.screenshot({path: '/tmp/prospector-web-shop.png'});
  await page.reload();
  await page.waitForTimeout(5000);
  await page.screenshot({path: '/tmp/prospector-web-reload.png'});
  const mobile = await browser.newContext({viewport:{width:844,height:390}, deviceScaleFactor:1, isMobile:true, hasTouch:true});
  const phone = await mobile.newPage();
  phone.on('pageerror', e => errors.push(String(e)));
  await phone.goto(url);
  await phone.waitForTimeout(6000);
  // The 960×640 game is letterboxed to 585×390 on this landscape phone.
  const point = (x,y) => ({x:129.5+x*390/640, y:y*390/640});
  let p = point(480,335); await phone.touchscreen.tap(p.x,p.y);
  await phone.waitForTimeout(250);
  p = point(480,315); await phone.touchscreen.tap(p.x,p.y);
  await phone.waitForTimeout(250);
  const cdp = await mobile.newCDPSession(phone);
  const right=point(180,575), jet=point(870,575);
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...right,id:0},{...jet,id:1}]});
  await phone.waitForTimeout(1500);
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  await phone.waitForTimeout(1200);
  await phone.screenshot({path:'/tmp/prospector-web-touch.png'});
  assert.deepEqual(errors, [], 'Browser errors');
  console.log('Browser load, desktop input, and simultaneous touch sequence completed without errors; inspect screenshots for visual outcomes.');
  await browser.close();
})().catch(e=>{console.error(e); process.exit(1)});
